tap "caskroom/cask"
tap "caskroom/fonts"

cask "1password"
cask "visual-studio-code"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "keybase"
cask "minikube"
cask "screenhero"
cask "slack"
cask "virtualbox"
cask "zoomus"

brew "hub"
brew "jq"
brew "kubectl"
brew "watch"
